print("hello world")
print("THIS IS BHARATH",999,sep='***',end='\n')
print("Happy to be the testing academy part",sep='***')
print(5 + 5, 9 * 6, " " " ", 8 / 3)
print("Hi", "bye", "sir")
print("Testing", 555 ,"Academy by pro mode",123,"pramod ji",sep='*/@',end='*****')
print(111,222,333)
print("END")